### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by ghost** [aschmelyun/github-receipts#11]
Would love to see support for emojis
🤪🤔🤪🤔🤪🤔🤪🤔🤪🤔🤪🤔🤪🤔🤪🤔🤪🤔🤪🤪🤔🤪🤔🤪🤔🤪🤔🤪🤔🤪😛🤪😛🤪🙉🙉🙉🙉🙊🙊🙊🙀👺😿👺😫👺💩👹🙀😹😹😿👾❤💘❤💝❤️‍🔥💞❣️💯💔🤚☻️🤞💫💬🤌🤏🖐🗯🤞🗯💪🙏💪🤙☝️🙏💅🤳👎👃🙏👐✍️👍👎🧔👧👩👨‍🦳👱🧒👁🫁👅👄👧👁👁🫁👁🫁👁🫁👁👁👦👩‍🦰👨‍🦱🧔👦🙆🙅‍♀️🙆👵👱‍♂️🙍‍♂️👱‍♂️🙋‍♀️🧏‍♂️🙎🙆👴💁‍♂️👵🙎‍♀️🙅👩‍⚕️👨‍🌾👨‍⚖️🧑‍🎓👨‍⚖️🧑‍🎓👨‍⚕️🧑‍🎓🧑‍🏫

**Comment by aschmelyun** [comment]
Same! It would have to be a library that converts them to small images and then replaces the unicode with an inline image.

**Comment by ghost** [comment]
Jokes aside, it seems ESC POS does have limited bitmap support. If I find some free time next weekend I'll gladly push a PR
