### ISSUE TITLE
Clarify LICENSE?

### ISSUE THREAD

**Issue by andypiper** [aschmelyun/github-receipts#2]
Hi there, the [Hackster.io article](https://www.hackster.io/news/andrew-schmelyun-s-raspberry-pi-powered-printer-makes-github-issues-into-physical-tickets-d70349cd4dc7) about this project says the code is available under "an unspecified open source license", could the usage terms be clarified? Thanks! 🙏🏻

**Comment by aschmelyun** [comment]
Done! Code is MIT Licensed.
